typography_spectrum: 0.17744525684975088
color:
  brandStrength: 0.3741606257390231
  lightness: 0.8923301347531378
  saturation: 0.6095534295309335
  rhythmicContrast: 0.30301754525862634
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.18382241833023727
author:
  name: Frederik Van Genechten
  email: info@thinksmart.be
  url: www.thinksmart.be
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/73eb7cb2-5089-4497-bebf-f1ebc2442243.svg
name: ThinkSmart
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bd9285f0-8d1d-4f3d-8796-0fba9e63e916.png
title: Graphic Design - Printing - Props
description: 'for Film, Television and Theatre'
